### PR TITLE
Various tweaks to scripts and a few graphics

### PR DESCRIPTION
**Pull request by TheMushrunt**
i know Pull Requests aren't the best way to handle this but i feel like these are all things that would enhance the 3AIR experience fairly well, regardless of how minor they are.
**FIXES:**
-Background (off-white) colored pixels in Continue sprites for Sonic and Tails have been removed
-DEZ's Centrifuge Tube Intersections will no longer make the game freak out, and will now force the player off of them, when entering Debug Mode
**IMPROVEMENTS:**
-Knuckles's Cutscene palette no longer loads in with AIR's Extended Character Palettes (prevents graphical issues w/ stuff that used the same palette line)
-Sonic, when falling in the beginning of the S&K title screen, moves with the extended screen width (makes it so he lands the same way in every possible width, to line up with the 4:3 version)
-Big Arms doesn't cause the player to reset animations after being defeated (unnecessary in AIR, as far as i can tell)
-The first set of spikes in the burning section of AIZ1 do not come down immediately so the player has an opportunity to move past them quicker when playing through the level
-The hollow tree in AIZ1 no longer caps the horizontal movement of the player when exiting the tree
The last two changes will definitely alter the best possible times for AIZ1, so if necessary, I can modify the changes to not apply to Time Attack.

### CODE REVIEW

**Comment by Eukaryot** [comment]
Hey Mushrunt,
Thanks for your contributions!
From what I've seen, this looks very good and I'm going to merge most of your changes. Maybe with the exception of the last two changes, as you've mentioned as well. But all of the rest feels like clear improvements.
Hoever, please note that the merge is probably not going to happen before I have a bit more time for S3AIR (it's difficulty right now...), so I can properly review everything.

**Comment by TheMushrunt** [comment]
thank you VERY MUCH Eukaryot. it really means a lot to me that you'd wanna merge the changes, even if it's not all of them. i've loved modding the game and being able to have things i changed put into it is such a nice feeling. i can wait as long as you want before you merge it, by the way. i understand your situation

**Comment by Eukaryot** [comment]
Most of your fixes and improvements are now merged with this commit: https://github.com/Eukaryot/sonic3air/commit/231be19b1b5234ebd18a280899a0afc2459b2032
I've also added you to the list of contributors in the readme, and marked the code changes accordingly. If you have any objections, just let me know.
And once again, thank you for your contributions!

**Comment by TheMushrunt** [comment]
i don't have any objections, so it's nice to see them getting merged in.
if i find anything new to add or improve, you have my permission to merge any commits from the fork i've had of your repo, if you want to do so.

**Pull request closed without merging**
